In [6]:
import numpy as np
import pandas as pd
import sqlite3
import os

In [3]:
!pwd

/home/kodolamacz/bootcamp-2018-09/Pandas

In [ ]:
import os

In [2]:
os.getcwd()

'/home/kodolamacz/bootcamp-2018-09/Pandas'

In [7]:
airlines = pd.read_csv("nycflights13_airlines.csv.gz", compression="gzip", comment="#")
airports = pd.read_csv("nycflights13_airports.csv.gz", compression="gzip", comment="#")
flights = pd.read_csv("nycflights13_flights.csv.gz", compression="gzip", comment="#")
planes = pd.read_csv("nycflights13_planes.csv.gz", compression="gzip", comment="#")
weather = pd.read_csv("nycflights13_weather.csv.gz", compression="gzip", comment="#")

In [ ]:
airlines = pd.read_csv("nycflights13_airlines.csv.gz", comment="#")

In [ ]:
airlines.head()

In [ ]:
airports.head()

In [ ]:
flights.head()

In [ ]:
planes.head()

In [ ]:
weather.head()

In [ ]:
# pd.read_csv("/home/kodolamacz/bootcamp-2018-07/Pandas/nycflights13_airlines.csv.gz", )
# pd.read_csv("/home/kodolamacz/Pobrane/nycflights13_airlines.csv.gz",)

In [ ]:
os.getcwd()

In [4]:
os.path.join("folder1", "folder2")

'folder1/folder2'

In [5]:
db_name = 'nycflights13.db'
os.path.join(os.getcwd(), db_name)

'/home/kodolamacz/bootcamp-2018-09/Pandas/nycflights13.db'

In [ ]:
db_name = 'nycflights13.db'
os.remove(os.path.join(os.getcwd(), db_name))

In [8]:
db_name = 'nycflights13.db'
con = sqlite3.connect(os.path.join(os.getcwd(), db_name))

planes.to_sql("planes", con, if_exists="replace")
airlines.to_sql("airlines", con, if_exists="replace")
flights.to_sql("flights", con, if_exists="replace")
airports.to_sql("airports", con, if_exists="replace")
weather.to_sql("weather", con, if_exists="replace")

# Przyk≈Çadowe zapytania

In [10]:
# wszystko jak leci
sql_result = pd.read_sql_query("SELECT * FROM planes", con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
5,5,N105UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
6,6,N107US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
7,7,N108UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
8,8,N109UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
9,9,N110UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
10,10,N11106,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
11,11,N11107,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
12,12,N11109,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
13,13,N11113,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
14,14,N11119,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
15,15,N11121,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
16,16,N11127,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
17,17,N11137,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
18,18,N11140,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
19,19,N11150,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
20,20,N11155,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
21,21,N11164,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
22,22,N11165,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
23,23,N11176,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
24,24,N11181,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
25,25,N11184,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
26,26,N11187,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
27,27,N11189,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
28,28,N11191,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
29,29,N11192,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
3292,3292,N984DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3293,3293,N985AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3294,3294,N985DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3295,3295,N986AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3296,3296,N986DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3297,3297,N987AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3298,3298,N987DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3299,3299,N988AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3300,3300,N988DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3301,3301,N989AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3302,3302,N989DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3303,3303,N990AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3304,3304,N990DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3305,3305,N991AT,NaN,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3306,3306,N991DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3307,3307,N992AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3308,3308,N992DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3309,3309,N993AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3310,3310,N993DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3311,3311,N994AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3312,3312,N994DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3313,3313,N995AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3314,3314,N995DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3315,3315,N996AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3316,3316,N996DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3317,3317,N997AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3318,3318,N997DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3319,3319,N998AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3320,3320,N998DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3321,3321,N999DN,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet

In [11]:
# wszystkie wiersze, ale tylko 2 kolumny
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes", con)
sql_result

     tailnum    year
0     N10156  2004.0
1     N102UW  1998.0
2     N103US  1999.0
3     N104UW  1999.0
4     N10575  2002.0
5     N105UW  1999.0
6     N107US  1999.0
7     N108UW  1999.0
8     N109UW  1999.0
9     N110UW  1999.0
10    N11106  2002.0
11    N11107  2002.0
12    N11109  2002.0
13    N11113  2002.0
14    N11119  2002.0
15    N11121  2003.0
16    N11127  2003.0
17    N11137  2003.0
18    N11140  2003.0
19    N11150  2003.0
20    N11155  2004.0
21    N11164  2004.0
22    N11165  2004.0
23    N11176  2004.0
24    N11181  2005.0
25    N11184  2005.0
26    N11187  2005.0
27    N11189  2005.0
28    N11191  2005.0
29    N11192  2005.0
...      ...     ...
3292  N984DL  1991.0
3293  N985AT  2001.0
3294  N985DL  1991.0
3295  N986AT  2001.0
3296  N986DL  1991.0
3297  N987AT  2001.0
3298  N987DL  1991.0
3299  N988AT  2001.0
3300  N988DL  1991.0
3301  N989AT  2001.0
3302  N989DL  1991.0
3303  N990AT  2001.0
3304  N990DL  1991.0
3305  N991AT     NaN
3306  N991DL  1991.0
3307  N992AT  2002.0
3308  N992DL  1991.0
3309  N993AT  2002.0
3310  N993DL  1991.0
3311  N994AT  2002.0
3312  N994DL  1991.0
3313  N995AT  2002.0
3314  N995DL  1991.0
3315  N996AT  2002.0
3316  N996DL  1991.0
3317  N997AT  2002.0
3318  N997DL  1992.0
3319  N998AT  2002.0
3320  N998DL  1992.0
3321  N999DN  1992.0

[3322 rows x 2 columns]

In [12]:
# niektore wiersze, ale tylko 2 kolumny
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes WHERE year >= 2000", con)
sql_result

     tailnum    year
0     N10156  2004.0
1     N10575  2002.0
2     N11106  2002.0
3     N11107  2002.0
4     N11109  2002.0
5     N11113  2002.0
6     N11119  2002.0
7     N11121  2003.0
8     N11127  2003.0
9     N11137  2003.0
10    N11140  2003.0
11    N11150  2003.0
12    N11155  2004.0
13    N11164  2004.0
14    N11165  2004.0
15    N11176  2004.0
16    N11181  2005.0
17    N11184  2005.0
18    N11187  2005.0
19    N11189  2005.0
20    N11191  2005.0
21    N11192  2005.0
22    N11193  2005.0
23    N11194  2005.0
24    N11199  2006.0
25    N11206  2000.0
26    N11535  2001.0
27    N11536  2001.0
28    N11539  2001.0
29    N11544  2002.0
...      ...     ...
1995  N967WN  2011.0
1996  N968AT  2001.0
1997  N968WN  2011.0
1998  N969AT  2001.0
1999  N969WN  2011.0
2000  N970AT  2001.0
2001  N971AT  2001.0
2002  N972AT  2001.0
2003  N974AT  2002.0
2004  N975AT  2002.0
2005  N977AT  2002.0
2006  N978AT  2002.0
2007  N978SW  2004.0
2008  N979AT  2002.0
2009  N980AT  2002.0
2010  N981AT  2002.0
2011  N982AT  2002.0
2012  N985AT  2001.0
2013  N986AT  2001.0
2014  N987AT  2001.0
2015  N988AT  2001.0
2016  N989AT  2001.0
2017  N990AT  2001.0
2018  N992AT  2002.0
2019  N993AT  2002.0
2020  N994AT  2002.0
2021  N995AT  2002.0
2022  N996AT  2002.0
2023  N997AT  2002.0
2024  N998AT  2002.0

[2025 rows x 2 columns]

In [13]:
# niektore wiersze, ale tylko 2 kolumny, laczenie warunkow
sql_result = pd.read_sql_query("SELECT * FROM planes WHERE year >= 2000 and seats > 100", con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,34,N11206,2000.0,Fixed wing multi engine,BOEING,737-824,2,149,None,Turbo-fan
1,46,N117UW,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
2,47,N118US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
3,48,N119US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
4,70,N121UW,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
5,77,N122US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
6,78,N123UW,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
7,79,N124US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
8,86,N125UW,2009.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
9,87,N126UW,2009.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
10,88,N127UW,2010.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
11,89,N128UW,2010.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
12,215,N150UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
13,216,N151UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
14,218,N152UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
15,221,N153UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
16,223,N154UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
17,228,N155UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
18,230,N156UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
19,233,N157UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
20,246,N1607B,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
21,247,N1608,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
22,248,N1609,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
23,249,N1610D,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
24,251,N1611B,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
25,252,N1612T,2001.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
26,253,N1613B,2001.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
27,261,N161UW,2001.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,2,199,None,Turbo-jet
28,265,N162UW,2001.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,2,199,None,Turbo-jet
29,266,N163US,2001.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,2,199,None,Turbo-jet
...,...,...,...,...,...,...,...,...,...,...
1284,3139,N941WN,2009.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1285,3143,N942WN,2009.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1286,3148,N943WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1287,3153,N944WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1288,3158,N945WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1289,3162,N946WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1290,3166,N947WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1291,3171,N948WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1292,3175,N949WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1293,3179,N950WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1294,3184,N951WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1295,3189,N952WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1296,3195,N953WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1297,3199,N954WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1298,3204,N955WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1299,3210,N956WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1300,3215,N957WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1301,3220,N958WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1302,3225,N959WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1303,3229,N960WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1304,3234,N961WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1305,3237,N962WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1306,3242,N963WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1307,3246,N964WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1308,3249,N965DN,2000.0,Fixed wing multi engine,BOEING,MD-90-30,2,142,None,Turbo-fan
1309,3251,N965WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1310,3254,N966WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1311,3258,N967WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1312,3261,N968WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1313,3264,N969WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan

In [14]:
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes WHERE year == 2000 or year==2001", con)
sql_result

    tailnum    year
0    N11206  2000.0
1    N11535  2001.0
2    N11536  2001.0
3    N11539  2001.0
4    N117UW  2000.0
5    N118US  2000.0
6    N119US  2000.0
7    N121UW  2000.0
8    N122US  2000.0
9    N123UW  2000.0
10   N124US  2000.0
11   N12540  2001.0
12   N12900  2001.0
13   N12921  2000.0
14   N12922  2000.0
15   N12924  2000.0
16   N12996  2000.0
17   N13538  2001.0
18   N13903  2001.0
19   N13908  2001.0
20   N13913  2001.0
21   N13914  2001.0
22   N13988  2000.0
23   N13989  2000.0
24   N13992  2000.0
25   N13994  2000.0
26   N13995  2000.0
27   N13997  2000.0
28   N14542  2001.0
29   N14902  2001.0
..      ...     ...
498  N937AT  2001.0
499  N950AT  2000.0
500  N951AT  2000.0
501  N952AT  2000.0
502  N953AT  2000.0
503  N954AT  2000.0
504  N955AT  2000.0
505  N956AT  2000.0
506  N957AT  2000.0
507  N958AT  2001.0
508  N959AT  2001.0
509  N960AT  2001.0
510  N961AT  2001.0
511  N963AT  2001.0
512  N964AT  2001.0
513  N965AT  2001.0
514  N965DN  2000.0
515  N966AT  2001.0
516  N967AT  2001.0
517  N968AT  2001.0
518  N969AT  2001.0
519  N970AT  2001.0
520  N971AT  2001.0
521  N972AT  2001.0
522  N985AT  2001.0
523  N986AT  2001.0
524  N987AT  2001.0
525  N988AT  2001.0
526  N989AT  2001.0
527  N990AT  2001.0

[528 rows x 2 columns]

# 1

In [15]:
sql_result = pd.read_sql_query("SELECT DISTINCT engine FROM planes", con)
sql_result

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

In [17]:
pd.unique(planes["engine"])

array(['Turbo-fan', 'Turbo-jet', 'Reciprocating', '4 Cycle',
       'Turbo-shaft', 'Turbo-prop'], dtype=object)

In [18]:
wynik = pd.DataFrame(pd.unique(planes["engine"]))
wynik = wynik.rename({0: "engine"}, axis=1)
wynik

               0
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

In [19]:
wynik.columns = ["engine"]

In [ ]:
planes.engine.unique()

In [ ]:
wynik = pd.DataFrame({"engine" : planes.engine.unique()})
# wynik.columns = ["engine"]
wynik

In [20]:
pd.__version__

'0.23.0'

# 2

In [21]:
sql_result = pd.read_sql_query("SELECT DISTINCT type, manufacturer, model, seats, engine FROM planes", con)
sql_result

,type,manufacturer,model,seats,engine
0,Fixed wing multi engine,EMBRAER,EMB-145XR,55,Turbo-fan
1,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,182,Turbo-fan
2,Fixed wing multi engine,EMBRAER,EMB-145LR,55,Turbo-fan
3,Fixed wing multi engine,BOEING,737-824,149,Turbo-fan
4,Fixed wing multi engine,BOEING,767-332,330,Turbo-fan
5,Fixed wing multi engine,BOEING,757-224,178,Turbo-jet
6,Fixed wing multi engine,AIRBUS,A320-214,182,Turbo-fan
7,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,95,Turbo-fan
8,Fixed wing multi engine,BOEING,737-724,149,Turbo-jet
9,Fixed wing multi engine,BOEING,737-524,149,Turbo-fan
10,Fixed wing multi engine,BOEING,767-3P6,290,Turbo-fan
11,Fixed wing multi engine,AIRBUS,A321-211,199,Turbo-fan
12,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,199,Turbo-jet
13,Fixed wing multi engine,BOEING,737-76N,149,Turbo-fan
14,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,20,Turbo-fan
15,Fixed wing multi engine,BOEING,737-7H4,140,Turbo-fan
16,Fixed wing single engine,CESSNA,150,2,Reciprocating
17,Fixed wing multi engine,CESSNA,421C,8,Reciprocating
18,Fixed wing multi engine,BOEING,777-222,400,Turbo-fan
19,Fixed wing multi engine,BOEING,787-8,260,Turbo-fan
20,Fixed wing multi engine,BOEING,767-201,255,Turbo-jet
21,Fixed wing multi engine,BOEING,737-705,149,Turbo-fan
22,Fixed wing multi engine,BOEING,777-200,400,Turbo-jet
23,Fixed wing multi engine,BOEING,737-924ER,191,Turbo-fan
24,Fixed wing multi engine,EMBRAER,EMB-145,55,Turbo-jet
25,Fixed wing multi engine,AIRBUS INDUSTRIE,A340-313,375,Turbo-jet
26,Fixed wing multi engine,BOEING,737-732,149,Turbo-fan
27,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-114,145,Turbo-fan
28,Fixed wing multi engine,BOEING,737-990,149,Turbo-jet
29,Fixed wing multi engine,BOEING,737-924,191,Turbo-fan
...,...,...,...,...,...
119,Fixed wing multi engine,BOEING,737-3TO,149,Turbo-jet
120,Fixed wing multi engine,BOEING,737-317,149,Turbo-jet
121,Fixed wing multi engine,BOEING,737-3T5,149,Turbo-jet
122,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-112,179,Turbo-fan
123,Fixed wing multi engine,BOEING,757-231,178,Turbo-fan
124,Fixed wing multi engine,GULFSTREAM AEROSPACE,G1159B,22,Turbo-jet
125,Fixed wing single engine,CESSNA,172N,4,Reciprocating
126,Fixed wing multi engine,BOEING,757-212,178,Turbo-jet
127,Fixed wing multi engine,BOEING,737-7AD,128,Turbo-jet
128,Fixed wing multi engine,BOEING,737-7Q8,149,Turbo-fan
129,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-132,179,Turbo-jet
130,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-131,179,Turbo-jet
131,Fixed wing multi engine,AIRBUS,A330-323,379,Turbo-fan
132,Fixed wing multi engine,CANADAIR,CL-600-2B19,55,Turbo-fan
133,Fixed wing multi engine,BOEING,767-432ER,300,Turbo-jet
134,Fixed wing multi engine,BOEING,737-8H4,140,Turbo-fan
135,Fixed wing multi engine,AIRBUS,A319-132,179,Turbo-fan
136,Fixed wing multi engine,CANADAIR LTD,CF-5D,2,Turbo-jet
137,Fixed wing multi engine,AIRBUS INDUSTRIE,A330-223,379,Turbo-jet
138,Fixed wing multi engine,AIRBUS,A319-131,179,Turbo-jet
139,Fixed wing multi engine,AIRBUS,A330-223,379,Turbo-fan
140,Fixed wing multi engine,BOEING,777-232,400,Turbo-jet
141,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,142,Turbo-jet
142,Fixed wing multi engine,BOEING,757-26D,178,Turbo-jet
143,Fixed wing multi engine,MCDONNELL DOUGLAS,MD-90-30,142,Turbo-jet
144,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,142,Turbo-fan
145,Fixed wing multi engine,AVIONS MARCEL DASSAULT,MYSTERE FALCON 900,12,Turbo-fan
146,Fixed wing multi engine,MCDONNELL DOUGLAS,MD-90-30,142,Turbo-fan
147,Fixed wing multi engine,BOEING,MD-90-30,142,Turbo-fan
148,Fixed wing multi engine,BOEING,757-2B7,178,Turbo-fan

In [31]:
type(planes)

pandas.core.frame.DataFrame

In [27]:
# wybraƒá te kolumny a potem usunƒÖƒá duplikaty
wynik = planes[["type", "manufacturer", "model", "seats", "engine"]].drop_duplicates()
wynik.shape, sql_result.shape

((149, 5), (149, 5))

In [32]:
wynik = wynik.reset_index(drop=True)
wynik

,type,manufacturer,model,seats,engine
0,Fixed wing multi engine,EMBRAER,EMB-145XR,55,Turbo-fan
1,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,182,Turbo-fan
2,Fixed wing multi engine,EMBRAER,EMB-145LR,55,Turbo-fan
3,Fixed wing multi engine,BOEING,737-824,149,Turbo-fan
4,Fixed wing multi engine,BOEING,767-332,330,Turbo-fan
5,Fixed wing multi engine,BOEING,757-224,178,Turbo-jet
6,Fixed wing multi engine,AIRBUS,A320-214,182,Turbo-fan
7,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,95,Turbo-fan
8,Fixed wing multi engine,BOEING,737-724,149,Turbo-jet
9,Fixed wing multi engine,BOEING,737-524,149,Turbo-fan
10,Fixed wing multi engine,BOEING,767-3P6,290,Turbo-fan
11,Fixed wing multi engine,AIRBUS,A321-211,199,Turbo-fan
12,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,199,Turbo-jet
13,Fixed wing multi engine,BOEING,737-76N,149,Turbo-fan
14,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,20,Turbo-fan
15,Fixed wing multi engine,BOEING,737-7H4,140,Turbo-fan
16,Fixed wing single engine,CESSNA,150,2,Reciprocating
17,Fixed wing multi engine,CESSNA,421C,8,Reciprocating
18,Fixed wing multi engine,BOEING,777-222,400,Turbo-fan
19,Fixed wing multi engine,BOEING,787-8,260,Turbo-fan
20,Fixed wing multi engine,BOEING,767-201,255,Turbo-jet
21,Fixed wing multi engine,BOEING,737-705,149,Turbo-fan
22,Fixed wing multi engine,BOEING,777-200,400,Turbo-jet
23,Fixed wing multi engine,BOEING,737-924ER,191,Turbo-fan
24,Fixed wing multi engine,EMBRAER,EMB-145,55,Turbo-jet
25,Fixed wing multi engine,AIRBUS INDUSTRIE,A340-313,375,Turbo-jet
26,Fixed wing multi engine,BOEING,737-732,149,Turbo-fan
27,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-114,145,Turbo-fan
28,Fixed wing multi engine,BOEING,737-990,149,Turbo-jet
29,Fixed wing multi engine,BOEING,737-924,191,Turbo-fan
...,...,...,...,...,...
119,Fixed wing multi engine,BOEING,737-3TO,149,Turbo-jet
120,Fixed wing multi engine,BOEING,737-317,149,Turbo-jet
121,Fixed wing multi engine,BOEING,737-3T5,149,Turbo-jet
122,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-112,179,Turbo-fan
123,Fixed wing multi engine,BOEING,757-231,178,Turbo-fan
124,Fixed wing multi engine,GULFSTREAM AEROSPACE,G1159B,22,Turbo-jet
125,Fixed wing single engine,CESSNA,172N,4,Reciprocating
126,Fixed wing multi engine,BOEING,757-212,178,Turbo-jet
127,Fixed wing multi engine,BOEING,737-7AD,128,Turbo-jet
128,Fixed wing multi engine,BOEING,737-7Q8,149,Turbo-fan
129,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-132,179,Turbo-jet
130,Fixed wing multi engine,AIRBUS INDUSTRIE,A319-131,179,Turbo-jet
131,Fixed wing multi engine,AIRBUS,A330-323,379,Turbo-fan
132,Fixed wing multi engine,CANADAIR,CL-600-2B19,55,Turbo-fan
133,Fixed wing multi engine,BOEING,767-432ER,300,Turbo-jet
134,Fixed wing multi engine,BOEING,737-8H4,140,Turbo-fan
135,Fixed wing multi engine,AIRBUS,A319-132,179,Turbo-fan
136,Fixed wing multi engine,CANADAIR LTD,CF-5D,2,Turbo-jet
137,Fixed wing multi engine,AIRBUS INDUSTRIE,A330-223,379,Turbo-jet
138,Fixed wing multi engine,AIRBUS,A319-131,179,Turbo-jet
139,Fixed wing multi engine,AIRBUS,A330-223,379,Turbo-fan
140,Fixed wing multi engine,BOEING,777-232,400,Turbo-jet
141,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,142,Turbo-jet
142,Fixed wing multi engine,BOEING,757-26D,178,Turbo-jet
143,Fixed wing multi engine,MCDONNELL DOUGLAS,MD-90-30,142,Turbo-jet
144,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,142,Turbo-fan
145,Fixed wing multi engine,AVIONS MARCEL DASSAULT,MYSTERE FALCON 900,12,Turbo-fan
146,Fixed wing multi engine,MCDONNELL DOUGLAS,MD-90-30,142,Turbo-fan
147,Fixed wing multi engine,BOEING,MD-90-30,142,Turbo-fan
148,Fixed wing multi engine,BOEING,757-2B7,178,Turbo-fan

# 3

In [33]:
sql_result = pd.read_sql_query("SELECT COUNT(*), engine FROM planes GROUP BY engine", con)
sql_result

   COUNT(*)         engine
0         2        4 Cycle
1        28  Reciprocating
2      2750      Turbo-fan
3       535      Turbo-jet
4         2     Turbo-prop
5         5    Turbo-shaft

## tabela kontyngencji

In [38]:
wynik = planes.engine.value_counts()
type(wynik)

pandas.core.series.Series

In [47]:
pd.DataFrame(wynik).reset_index()

           index  engine
0      Turbo-fan    2750
1      Turbo-jet     535
2  Reciprocating      28
3    Turbo-shaft       5
4     Turbo-prop       2
5        4 Cycle       2

In [62]:
wynik = planes.engine.value_counts().reset_index()\
                    .sort_values(by="index")[["engine", "index"]]\
                    .reset_index(drop=True)
# wynik.columns = ["COUNT(*)", "engine"]
wynik = wynik.rename({"engine" : "COUNT(*)", "index": "engine"},
                     axis=1)
wynik

   COUNT(*)         engine
0         2        4 Cycle
1        28  Reciprocating
2      2750      Turbo-fan
3       535      Turbo-jet
4         2     Turbo-prop
5         5    Turbo-shaft

## groupby()

In [65]:
planes.groupby("engine").count()

               tailnum  year  type  manufacturer  model  engines  seats  speed
engine
4 Cycle              2     1     2             2      2        2      2      1
Reciprocating       28    21    28            28     28       28     28     12
Turbo-fan         2750  2697  2750          2750   2750     2750   2750      0
Turbo-jet          535   526   535           535    535      535    535      8
Turbo-prop           2     2     2             2      2        2      2      1
Turbo-shaft          5     5     5             5      5        5      5      1

In [64]:
planes.groupby("engine", as_index=False).count() # zlicza te, kt√≥re nie sƒÖ brakami danych

,engine,tailnum,year,type,manufacturer,model,engines,seats,speed
0,4 Cycle,2,1,2,2,2,2,2,1
1,Reciprocating,28,21,28,28,28,28,28,12
2,Turbo-fan,2750,2697,2750,2750,2750,2750,2750,0
3,Turbo-jet,535,526,535,535,535,535,535,8
4,Turbo-prop,2,2,2,2,2,2,2,1
5,Turbo-shaft,5,5,5,5,5,5,5,1

In [68]:
wynik2 = planes.groupby("engine", as_index=False).size() # zlicza wiersze, nie przejmuje siƒô brakami danych

In [75]:
wynik2.reset_index(drop=False).rename({0 : "COUNT(*)"},
                     axis=1)[["COUNT(*)", "engine"]]

   COUNT(*)         engine
0         2        4 Cycle
1        28  Reciprocating
2      2750      Turbo-fan
3       535      Turbo-jet
4         2     Turbo-prop
5         5    Turbo-shaft

## tabela przestawna

In [79]:
pd.pivot_table(planes[["engine"]],
               index=["engine"],
               aggfunc="size"
              ).reset_index()

          engine     0
0        4 Cycle     2
1  Reciprocating    28
2      Turbo-fan  2750
3      Turbo-jet   535
4     Turbo-prop     2
5    Turbo-shaft     5

# 4

In [81]:
sql_result = pd.read_sql_query("SELECT COUNT(*), engine, type FROM planes GROUP BY engine, type", con)
sql_result

   COUNT(*)         engine                      type
0         2        4 Cycle  Fixed wing single engine
1         5  Reciprocating   Fixed wing multi engine
2        23  Reciprocating  Fixed wing single engine
3      2750      Turbo-fan   Fixed wing multi engine
4       535      Turbo-jet   Fixed wing multi engine
5         2     Turbo-prop   Fixed wing multi engine
6         5    Turbo-shaft                Rotorcraft

## groupby()

In [86]:
planes.groupby(["engine", "type"]).size().reset_index()\
                            .rename({0:"COUNT(*)"}, axis=1)[["COUNT(*)","engine", "type"]]

   COUNT(*)         engine                      type
0         2        4 Cycle  Fixed wing single engine
1         5  Reciprocating   Fixed wing multi engine
2        23  Reciprocating  Fixed wing single engine
3      2750      Turbo-fan   Fixed wing multi engine
4       535      Turbo-jet   Fixed wing multi engine
5         2     Turbo-prop   Fixed wing multi engine
6         5    Turbo-shaft                Rotorcraft

In [106]:
planes.groupby(["engine", "type"]).size().reset_index()\
                            .rename({0:"COUNT(*)"}, axis=1).loc[:,::-1]

   COUNT(*)                      type         engine
0         2  Fixed wing single engine        4 Cycle
1         5   Fixed wing multi engine  Reciprocating
2        23  Fixed wing single engine  Reciprocating
3      2750   Fixed wing multi engine      Turbo-fan
4       535   Fixed wing multi engine      Turbo-jet
5         2   Fixed wing multi engine     Turbo-prop
6         5                Rotorcraft    Turbo-shaft

## tabela kontyngencji

In [89]:
pd.crosstab(planes.engine, planes.type)

type           Fixed wing multi engine  Fixed wing single engine  Rotorcraft
engine
4 Cycle                              0                         2           0
Reciprocating                        5                        23           0
Turbo-fan                         2750                         0           0
Turbo-jet                          535                         0           0
Turbo-prop                           2                         0           0
Turbo-shaft                          0                         0           5

In [109]:
wynik = pd.crosstab(planes.engine, planes.type).stack()
wynik

engine         type
4 Cycle        Fixed wing multi engine        0
               Fixed wing single engine       2
               Rotorcraft                     0
Reciprocating  Fixed wing multi engine        5
               Fixed wing single engine      23
               Rotorcraft                     0
Turbo-fan      Fixed wing multi engine     2750
               Fixed wing single engine       0
               Rotorcraft                     0
Turbo-jet      Fixed wing multi engine      535
               Fixed wing single engine       0
               Rotorcraft                     0
Turbo-prop     Fixed wing multi engine        2
               Fixed wing single engine       0
               Rotorcraft                     0
Turbo-shaft    Fixed wing multi engine        0
               Fixed wing single engine       0
               Rotorcraft                     5
dtype: int64

In [116]:
pd.crosstab(planes.engine, planes.type, margins=True)

type,Fixed wing multi engine,Fixed wing single engine,Rotorcraft,All
engine,,,,
4 Cycle,0,2,0,2
Reciprocating,5,23,0,28
Turbo-fan,2750,0,0,2750
Turbo-jet,535,0,0,535
Turbo-prop,2,0,0,2
Turbo-shaft,0,0,5,5
All,3292,25,5,3322

In [115]:
wynik = pd.crosstab(planes.engine, planes.type).unstack()
wynik = wynik.reset_index().rename({0 : "COUNT(*)"},axis=1)
wynik[wynik["COUNT(*)"] > 0].reset_index(drop=True)

                       type         engine  COUNT(*)
0   Fixed wing multi engine  Reciprocating         5
1   Fixed wing multi engine      Turbo-fan      2750
2   Fixed wing multi engine      Turbo-jet       535
3   Fixed wing multi engine     Turbo-prop         2
4  Fixed wing single engine        4 Cycle         2
5  Fixed wing single engine  Reciprocating        23
6                Rotorcraft    Turbo-shaft         5

## tabela przestawna

In [124]:
# te same trudnosci co przy crosstab, ale tutaj da sie je latwo ominac
wynik = pd.pivot_table(planes[["engine", "type"]],
               index=["engine"],
               columns = "type",
               aggfunc="size"
              ).stack().reset_index().rename({0 : "COUNT(*)"}, axis=1)
wynik["COUNT(*)"] = wynik["COUNT(*)"].astype(int)
wynik

          engine                      type  COUNT(*)
0        4 Cycle  Fixed wing single engine         2
1  Reciprocating   Fixed wing multi engine         5
2  Reciprocating  Fixed wing single engine        23
3      Turbo-fan   Fixed wing multi engine      2750
4      Turbo-jet   Fixed wing multi engine       535
5     Turbo-prop   Fixed wing multi engine         2
6    Turbo-shaft                Rotorcraft         5

In [95]:
pd.pivot_table(planes[["engine", "type"]],
               index=["engine", "type"],
               aggfunc="size"
              ).reset_index()

          engine                      type     0
0        4 Cycle  Fixed wing single engine     2
1  Reciprocating   Fixed wing multi engine     5
2  Reciprocating  Fixed wing single engine    23
3      Turbo-fan   Fixed wing multi engine  2750
4      Turbo-jet   Fixed wing multi engine   535
5     Turbo-prop   Fixed wing multi engine     2
6    Turbo-shaft                Rotorcraft     5

# 5

In [125]:
sql_result = pd.read_sql_query(
    "SELECT MIN(year), AVG(year), MAX(year), engine, manufacturer FROM planes GROUP BY engine, manufacturer", con)
sql_result

,MIN(year),AVG(year),MAX(year),engine,manufacturer
0,1975.0,1975.000000,1975.0,4 Cycle,CESSNA
1,NaN,NaN,NaN,4 Cycle,JOHN G HESS
2,NaN,NaN,NaN,Reciprocating,AMERICAN AIRCRAFT INC
3,2007.0,2007.000000,2007.0,Reciprocating,AVIAT AIRCRAFT INC
4,NaN,NaN,NaN,Reciprocating,BARKER JACK L
5,1959.0,1971.142857,1983.0,Reciprocating,CESSNA
6,2007.0,2007.000000,2007.0,Reciprocating,CIRRUS DESIGN CORP
7,1959.0,1959.000000,1959.0,Reciprocating,DEHAVILLAND
8,1956.0,1956.000000,1956.0,Reciprocating,DOUGLAS
9,2007.0,2007.000000,2007.0,Reciprocating,FRIEDEMANN JON
10,NaN,NaN,NaN,Reciprocating,HURLEY JAMES LARRY
11,1985.0,1985.000000,1985.0,Reciprocating,KILDALL GARY
12,NaN,NaN,NaN,Reciprocating,LAMBERT RICHARD
13,1985.0,1985.000000,1985.0,Reciprocating,LEBLANC GLENN T
14,1993.0,1993.000000,1993.0,Reciprocating,MARZ BARRY
15,NaN,NaN,NaN,Reciprocating,PAIR MIKE E
16,1968.0,1976.400000,1980.0,Reciprocating,PIPER
17,1985.0,1985.000000,1985.0,Reciprocating,STEWART MACO
18,2002.0,2007.281734,2013.0,Turbo-fan,AIRBUS
19,1992.0,1998.599251,2013.0,Turbo-fan,AIRBUS INDUSTRIE
20,1986.0,1986.000000,1986.0,Turbo-fan,AVIONS MARCEL DASSAULT
21,1965.0,2001.210400,2013.0,Turbo-fan,BOEING
22,1998.0,2004.486188,2013.0,Turbo-fan,BOMBARDIER INC
23,1997.0,1997.333333,1998.0,Turbo-fan,CANADAIR
24,1979.0,1979.000000,1979.0,Turbo-fan,CESSNA
25,1998.0,2003.613014,2013.0,Turbo-fan,EMBRAER
26,1992.0,1992.000000,1992.0,Turbo-fan,GULFSTREAM AEROSPACE
27,NaN,NaN,NaN,Turbo-fan,LEARJET INC
28,1986.0,1989.704545,1997.0,Turbo-fan,MCDONNELL DOUGLAS
29,1987.0,1989.737864,1993.0,Turbo-fan,MCDONNELL DOUGLAS AIRCRAFT CO
30,2002.0,2002.000000,2002.0,Turbo-jet,AIRBUS
31,1989.0,1997.439024,2004.0,Turbo-jet,AIRBUS INDUSTRIE
32,1984.0,1996.368272,2005.0,Turbo-jet,BOEING
33,1974.0,1974.000000,1974.0,Turbo-jet,CANADAIR LTD
34,1999.0,1999.000000,1999.0,Turbo-jet,EMBRAER
35,1976.0,1976.000000,1976.0,Turbo-jet,GULFSTREAM AEROSPACE
36,1975.0,1990.714286,1998.0,Turbo-jet,MCDONNELL DOUGLAS
37,1991.0,1991.928571,1992.0,Turbo-jet,MCDONNELL DOUGLAS CORPORATION
38,1967.0,1969.500000,1972.0,Turbo-prop,BEECH
39,2001.0,2001.000000,2001.0,Turbo-shaft,AGUSTA SPA
40,1975.0,1984.500000,1994.0,Turbo-shaft,BELL
41,2012.0,2012.000000,2012.0,Turbo-shaft,ROBINSON HELICOPTER CO
42,1985.0,1985.000000,1985.0,Turbo-shaft,SIKORSKY

## groupby()

In [134]:
# znale≈∫ƒá funkcjƒô, kt√≥ra w jednym ruchu policzy nam 3 funkcje agregujƒÖce: min, mean, max
planes.groupby(["engine", "manufacturer"])["year"].agg(["min", "mean", "max"])

                                                min         mean     max
engine        manufacturer
4 Cycle       CESSNA                         1975.0  1975.000000  1975.0
              JOHN G HESS                       NaN          NaN     NaN
Reciprocating AMERICAN AIRCRAFT INC             NaN          NaN     NaN
              AVIAT AIRCRAFT INC             2007.0  2007.000000  2007.0
              BARKER JACK L                     NaN          NaN     NaN
              CESSNA                         1959.0  1971.142857  1983.0
              CIRRUS DESIGN CORP             2007.0  2007.000000  2007.0
              DEHAVILLAND                    1959.0  1959.000000  1959.0
              DOUGLAS                        1956.0  1956.000000  1956.0
              FRIEDEMANN JON                 2007.0  2007.000000  2007.0
              HURLEY JAMES LARRY                NaN          NaN     NaN
              KILDALL GARY                   1985.0  1985.000000  1985.0
              LAMBERT RICHARD                   NaN          NaN     NaN
              LEBLANC GLENN T                1985.0  1985.000000  1985.0
              MARZ BARRY                     1993.0  1993.000000  1993.0
              PAIR MIKE E                       NaN          NaN     NaN
              PIPER                          1968.0  1976.400000  1980.0
              STEWART MACO                   1985.0  1985.000000  1985.0
Turbo-fan     AIRBUS                         2002.0  2007.281734  2013.0
              AIRBUS INDUSTRIE               1992.0  1998.599251  2013.0
              AVIONS MARCEL DASSAULT         1986.0  1986.000000  1986.0
              BOEING                         1965.0  2001.210400  2013.0
              BOMBARDIER INC                 1998.0  2004.486188  2013.0
              CANADAIR                       1997.0  1997.333333  1998.0
              CESSNA                         1979.0  1979.000000  1979.0
              EMBRAER                        1998.0  2003.613014  2013.0
              GULFSTREAM AEROSPACE           1992.0  1992.000000  1992.0
              LEARJET INC                       NaN          NaN     NaN
              MCDONNELL DOUGLAS              1986.0  1989.704545  1997.0
              MCDONNELL DOUGLAS AIRCRAFT CO  1987.0  1989.737864  1993.0
Turbo-jet     AIRBUS                         2002.0  2002.000000  2002.0
              AIRBUS INDUSTRIE               1989.0  1997.439024  2004.0
              BOEING                         1984.0  1996.368272  2005.0
              CANADAIR LTD                   1974.0  1974.000000  1974.0
              EMBRAER                        1999.0  1999.000000  1999.0
              GULFSTREAM AEROSPACE           1976.0  1976.000000  1976.0
              MCDONNELL DOUGLAS              1975.0  1990.714286  1998.0
              MCDONNELL DOUGLAS CORPORATION  1991.0  1991.928571  1992.0
Turbo-prop    BEECH                          1967.0  1969.500000  1972.0
Turbo-shaft   AGUSTA SPA                     2001.0  2001.000000  2001.0
              BELL                           1975.0  1984.500000  1994.0
              ROBINSON HELICOPTER CO         2012.0  2012.000000  2012.0
              SIKORSKY                       1985.0  1985.000000  1985.0

In [156]:
wynik = planes.groupby(["engine", "manufacturer"], as_index=False)\
                            .agg({"year" : ["min", "mean", "max"]})
wynik["engine"]
wynik[("year", "min")]
wynik[[("year", "min"), ("year", "max")]]
wynik[[("engine", ""), ("manufacturer", ""), ("year", "min"), ("year", "mean"), ("year", "max")]]

           engine                   manufacturer    year
                                                     min         mean     max
0         4 Cycle                         CESSNA  1975.0  1975.000000  1975.0
1         4 Cycle                    JOHN G HESS     NaN          NaN     NaN
2   Reciprocating          AMERICAN AIRCRAFT INC     NaN          NaN     NaN
3   Reciprocating             AVIAT AIRCRAFT INC  2007.0  2007.000000  2007.0
4   Reciprocating                  BARKER JACK L     NaN          NaN     NaN
5   Reciprocating                         CESSNA  1959.0  1971.142857  1983.0
6   Reciprocating             CIRRUS DESIGN CORP  2007.0  2007.000000  2007.0
7   Reciprocating                    DEHAVILLAND  1959.0  1959.000000  1959.0
8   Reciprocating                        DOUGLAS  1956.0  1956.000000  1956.0
9   Reciprocating                 FRIEDEMANN JON  2007.0  2007.000000  2007.0
10  Reciprocating             HURLEY JAMES LARRY     NaN          NaN     NaN
11  Reciprocating                   KILDALL GARY  1985.0  1985.000000  1985.0
12  Reciprocating                LAMBERT RICHARD     NaN          NaN     NaN
13  Reciprocating                LEBLANC GLENN T  1985.0  1985.000000  1985.0
14  Reciprocating                     MARZ BARRY  1993.0  1993.000000  1993.0
15  Reciprocating                    PAIR MIKE E     NaN          NaN     NaN
16  Reciprocating                          PIPER  1968.0  1976.400000  1980.0
17  Reciprocating                   STEWART MACO  1985.0  1985.000000  1985.0
18      Turbo-fan                         AIRBUS  2002.0  2007.281734  2013.0
19      Turbo-fan               AIRBUS INDUSTRIE  1992.0  1998.599251  2013.0
20      Turbo-fan         AVIONS MARCEL DASSAULT  1986.0  1986.000000  1986.0
21      Turbo-fan                         BOEING  1965.0  2001.210400  2013.0
22      Turbo-fan                 BOMBARDIER INC  1998.0  2004.486188  2013.0
23      Turbo-fan                       CANADAIR  1997.0  1997.333333  1998.0
24      Turbo-fan                         CESSNA  1979.0  1979.000000  1979.0
25      Turbo-fan                        EMBRAER  1998.0  2003.613014  2013.0
26      Turbo-fan           GULFSTREAM AEROSPACE  1992.0  1992.000000  1992.0
27      Turbo-fan                    LEARJET INC     NaN          NaN     NaN
28      Turbo-fan              MCDONNELL DOUGLAS  1986.0  1989.704545  1997.0
29      Turbo-fan  MCDONNELL DOUGLAS AIRCRAFT CO  1987.0  1989.737864  1993.0
30      Turbo-jet                         AIRBUS  2002.0  2002.000000  2002.0
31      Turbo-jet               AIRBUS INDUSTRIE  1989.0  1997.439024  2004.0
32      Turbo-jet                         BOEING  1984.0  1996.368272  2005.0
33      Turbo-jet                   CANADAIR LTD  1974.0  1974.000000  1974.0
34      Turbo-jet                        EMBRAER  1999.0  1999.000000  1999.0
35      Turbo-jet           GULFSTREAM AEROSPACE  1976.0  1976.000000  1976.0
36      Turbo-jet              MCDONNELL DOUGLAS  1975.0  1990.714286  1998.0
37      Turbo-jet  MCDONNELL DOUGLAS CORPORATION  1991.0  1991.928571  1992.0
38     Turbo-prop                          BEECH  1967.0  1969.500000  1972.0
39    Turbo-shaft                     AGUSTA SPA  2001.0  2001.000000  2001.0
40    Turbo-shaft                           BELL  1975.0  1984.500000  1994.0
41    Turbo-shaft         ROBINSON HELICOPTER CO  2012.0  2012.000000  2012.0
42    Turbo-shaft                       SIKORSKY  1985.0  1985.000000  1985.0

In [152]:
wynik = planes.groupby(["engine", "manufacturer"]).describe()

In [154]:
wynik = wynik[[("year", "min"), ("year", "mean"), ("year", "max")]].reset_index()
wynik.columns = ["engine", "manufacturer", "MIN(year)", "AVG(year)", "MAX(year)"]
wynik

,engine,manufacturer,MIN(year),AVG(year),MAX(year)
0,4 Cycle,CESSNA,1975.0,1975.000000,1975.0
1,4 Cycle,JOHN G HESS,NaN,NaN,NaN
2,Reciprocating,AMERICAN AIRCRAFT INC,NaN,NaN,NaN
3,Reciprocating,AVIAT AIRCRAFT INC,2007.0,2007.000000,2007.0
4,Reciprocating,BARKER JACK L,NaN,NaN,NaN
5,Reciprocating,CESSNA,1959.0,1971.142857,1983.0
6,Reciprocating,CIRRUS DESIGN CORP,2007.0,2007.000000,2007.0
7,Reciprocating,DEHAVILLAND,1959.0,1959.000000,1959.0
8,Reciprocating,DOUGLAS,1956.0,1956.000000,1956.0
9,Reciprocating,FRIEDEMANN JON,2007.0,2007.000000,2007.0
10,Reciprocating,HURLEY JAMES LARRY,NaN,NaN,NaN
11,Reciprocating,KILDALL GARY,1985.0,1985.000000,1985.0
12,Reciprocating,LAMBERT RICHARD,NaN,NaN,NaN
13,Reciprocating,LEBLANC GLENN T,1985.0,1985.000000,1985.0
14,Reciprocating,MARZ BARRY,1993.0,1993.000000,1993.0
15,Reciprocating,PAIR MIKE E,NaN,NaN,NaN
16,Reciprocating,PIPER,1968.0,1976.400000,1980.0
17,Reciprocating,STEWART MACO,1985.0,1985.000000,1985.0
18,Turbo-fan,AIRBUS,2002.0,2007.281734,2013.0
19,Turbo-fan,AIRBUS INDUSTRIE,1992.0,1998.599251,2013.0
20,Turbo-fan,AVIONS MARCEL DASSAULT,1986.0,1986.000000,1986.0
21,Turbo-fan,BOEING,1965.0,2001.210400,2013.0
22,Turbo-fan,BOMBARDIER INC,1998.0,2004.486188,2013.0
23,Turbo-fan,CANADAIR,1997.0,1997.333333,1998.0
24,Turbo-fan,CESSNA,1979.0,1979.000000,1979.0
25,Turbo-fan,EMBRAER,1998.0,2003.613014,2013.0
26,Turbo-fan,GULFSTREAM AEROSPACE,1992.0,1992.000000,1992.0
27,Turbo-fan,LEARJET INC,NaN,NaN,NaN
28,Turbo-fan,MCDONNELL DOUGLAS,1986.0,1989.704545,1997.0
29,Turbo-fan,MCDONNELL DOUGLAS AIRCRAFT CO,1987.0,1989.737864,1993.0
30,Turbo-jet,AIRBUS,2002.0,2002.000000,2002.0
31,Turbo-jet,AIRBUS INDUSTRIE,1989.0,1997.439024,2004.0
32,Turbo-jet,BOEING,1984.0,1996.368272,2005.0
33,Turbo-jet,CANADAIR LTD,1974.0,1974.000000,1974.0
34,Turbo-jet,EMBRAER,1999.0,1999.000000,1999.0
35,Turbo-jet,GULFSTREAM AEROSPACE,1976.0,1976.000000,1976.0
36,Turbo-jet,MCDONNELL DOUGLAS,1975.0,1990.714286,1998.0
37,Turbo-jet,MCDONNELL DOUGLAS CORPORATION,1991.0,1991.928571,1992.0
38,Turbo-prop,BEECH,1967.0,1969.500000,1972.0
39,Turbo-shaft,AGUSTA SPA,2001.0,2001.000000,2001.0
40,Turbo-shaft,BELL,1975.0,1984.500000,1994.0
41,Turbo-shaft,ROBINSON HELICOPTER CO,2012.0,2012.000000,2012.0
42,Turbo-shaft,SIKORSKY,1985.0,1985.000000,1985.0

## pivot table

In [159]:
pd.pivot_table(planes[["engine", "year", "manufacturer"]],
               index=["engine", "manufacturer"],
               aggfunc=["min", "mean", "max"]
              ).reset_index()

           engine                   manufacturer     min         mean     max
                                                    year         year    year
0         4 Cycle                         CESSNA  1975.0  1975.000000  1975.0
1         4 Cycle                    JOHN G HESS     NaN          NaN     NaN
2   Reciprocating          AMERICAN AIRCRAFT INC     NaN          NaN     NaN
3   Reciprocating             AVIAT AIRCRAFT INC  2007.0  2007.000000  2007.0
4   Reciprocating                  BARKER JACK L     NaN          NaN     NaN
5   Reciprocating                         CESSNA  1959.0  1971.142857  1983.0
6   Reciprocating             CIRRUS DESIGN CORP  2007.0  2007.000000  2007.0
7   Reciprocating                    DEHAVILLAND  1959.0  1959.000000  1959.0
8   Reciprocating                        DOUGLAS  1956.0  1956.000000  1956.0
9   Reciprocating                 FRIEDEMANN JON  2007.0  2007.000000  2007.0
10  Reciprocating             HURLEY JAMES LARRY     NaN          NaN     NaN
11  Reciprocating                   KILDALL GARY  1985.0  1985.000000  1985.0
12  Reciprocating                LAMBERT RICHARD     NaN          NaN     NaN
13  Reciprocating                LEBLANC GLENN T  1985.0  1985.000000  1985.0
14  Reciprocating                     MARZ BARRY  1993.0  1993.000000  1993.0
15  Reciprocating                    PAIR MIKE E     NaN          NaN     NaN
16  Reciprocating                          PIPER  1968.0  1976.400000  1980.0
17  Reciprocating                   STEWART MACO  1985.0  1985.000000  1985.0
18      Turbo-fan                         AIRBUS  2002.0  2007.281734  2013.0
19      Turbo-fan               AIRBUS INDUSTRIE  1992.0  1998.599251  2013.0
20      Turbo-fan         AVIONS MARCEL DASSAULT  1986.0  1986.000000  1986.0
21      Turbo-fan                         BOEING  1965.0  2001.210400  2013.0
22      Turbo-fan                 BOMBARDIER INC  1998.0  2004.486188  2013.0
23      Turbo-fan                       CANADAIR  1997.0  1997.333333  1998.0
24      Turbo-fan                         CESSNA  1979.0  1979.000000  1979.0
25      Turbo-fan                        EMBRAER  1998.0  2003.613014  2013.0
26      Turbo-fan           GULFSTREAM AEROSPACE  1992.0  1992.000000  1992.0
27      Turbo-fan                    LEARJET INC     NaN          NaN     NaN
28      Turbo-fan              MCDONNELL DOUGLAS  1986.0  1989.704545  1997.0
29      Turbo-fan  MCDONNELL DOUGLAS AIRCRAFT CO  1987.0  1989.737864  1993.0
30      Turbo-jet                         AIRBUS  2002.0  2002.000000  2002.0
31      Turbo-jet               AIRBUS INDUSTRIE  1989.0  1997.439024  2004.0
32      Turbo-jet                         BOEING  1984.0  1996.368272  2005.0
33      Turbo-jet                   CANADAIR LTD  1974.0  1974.000000  1974.0
34      Turbo-jet                        EMBRAER  1999.0  1999.000000  1999.0
35      Turbo-jet           GULFSTREAM AEROSPACE  1976.0  1976.000000  1976.0
36      Turbo-jet              MCDONNELL DOUGLAS  1975.0  1990.714286  1998.0
37      Turbo-jet  MCDONNELL DOUGLAS CORPORATION  1991.0  1991.928571  1992.0
38     Turbo-prop                          BEECH  1967.0  1969.500000  1972.0
39    Turbo-shaft                     AGUSTA SPA  2001.0  2001.000000  2001.0
40    Turbo-shaft                           BELL  1975.0  1984.500000  1994.0
41    Turbo-shaft         ROBINSON HELICOPTER CO  2012.0  2012.000000  2012.0
42    Turbo-shaft                       SIKORSKY  1985.0  1985.000000  1985.0

# 6

In [173]:
sql_result = pd.read_sql_query(
    "SELECT * FROM planes WHERE speed IS NOT NULL", con)
sql_result.shape

(23, 10)

In [163]:
pd.notnull(planes.speed)

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
3292    False
3293    False
3294    False
3295    False
3296    False
3297    False
3298    False
3299    False
3300    False
3301    False
3302    False
3303    False
3304    False
3305    False
3306    False
3307    False
3308    False
3309    False
3310    False
3311    False
3312    False
3313    False
3314    False
3315    False
3316    False
3317    False
3318    False
3319    False
3320    False
3321    False
Name: speed, Length: 3322, dtype: bool

In [164]:
pd.notna(planes.speed)

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
3292    False
3293    False
3294    False
3295    False
3296    False
3297    False
3298    False
3299    False
3300    False
3301    False
3302    False
3303    False
3304    False
3305    False
3306    False
3307    False
3308    False
3309    False
3310    False
3311    False
3312    False
3313    False
3314    False
3315    False
3316    False
3317    False
3318    False
3319    False
3320    False
3321    False
Name: speed, Length: 3322, dtype: bool

In [165]:
pd.isnull(planes.speed)

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
        ...
3292    True
3293    True
3294    True
3295    True
3296    True
3297    True
3298    True
3299    True
3300    True
3301    True
3302    True
3303    True
3304    True
3305    True
3306    True
3307    True
3308    True
3309    True
3310    True
3311    True
3312    True
3313    True
3314    True
3315    True
3316    True
3317    True
3318    True
3319    True
3320    True
3321    True
Name: speed, Length: 3322, dtype: bool

In [166]:
pd.isna(planes.speed)

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
        ...
3292    True
3293    True
3294    True
3295    True
3296    True
3297    True
3298    True
3299    True
3300    True
3301    True
3302    True
3303    True
3304    True
3305    True
3306    True
3307    True
3308    True
3309    True
3310    True
3311    True
3312    True
3313    True
3314    True
3315    True
3316    True
3317    True
3318    True
3319    True
3320    True
3321    True
Name: speed, Length: 3322, dtype: bool

In [171]:
planes[pd.notnull(planes.speed)].shape

(23, 9)

In [172]:
planes.dropna(subset=["speed"]).shape

(23, 9)

# 7

In [176]:
sql_result = pd.read_sql_query(
    "SELECT tailnum FROM planes WHERE year >= 2010", con)
sql_result.shape

(301, 1)

In [181]:
pd.DataFrame(planes[planes.year >= 2010]["tailnum"].reset_index(drop=True))

    tailnum
0    N127UW
1    N128UW
2    N150UW
3    N151UW
4    N152UW
5    N153UW
6    N154UW
7    N155UW
8    N156UW
9    N157UW
10   N198UW
11   N199UW
12   N205FR
13   N206FR
14   N207FR
15   N208FR
16   N20904
17   N209FR
18   N210FR
19   N211FR
20   N213FR
21   N214FR
22   N216FR
23   N26906
24   N272PQ
25   N27477
26   N27901
27   N279PQ
28   N28457
29   N28478
..      ...
271  N913JB
272  N943WN
273  N944WN
274  N945WN
275  N946WN
276  N947WN
277  N948WN
278  N949WN
279  N950WN
280  N951WN
281  N952FR
282  N952WN
283  N953FR
284  N953WN
285  N954WN
286  N955WN
287  N956WN
288  N957WN
289  N958WN
290  N959WN
291  N960WN
292  N961WN
293  N962WN
294  N963WN
295  N964WN
296  N965WN
297  N966WN
298  N967WN
299  N968WN
300  N969WN

[301 rows x 1 columns]

In [183]:
planes[planes.year >= 2010][["tailnum"]].reset_index(drop=True) #podajemy listƒô jednoelementowƒÖ, dziƒôki temu mamy nadal DataFrame

    tailnum
0    N127UW
1    N128UW
2    N150UW
3    N151UW
4    N152UW
5    N153UW
6    N154UW
7    N155UW
8    N156UW
9    N157UW
10   N198UW
11   N199UW
12   N205FR
13   N206FR
14   N207FR
15   N208FR
16   N20904
17   N209FR
18   N210FR
19   N211FR
20   N213FR
21   N214FR
22   N216FR
23   N26906
24   N272PQ
25   N27477
26   N27901
27   N279PQ
28   N28457
29   N28478
..      ...
271  N913JB
272  N943WN
273  N944WN
274  N945WN
275  N946WN
276  N947WN
277  N948WN
278  N949WN
279  N950WN
280  N951WN
281  N952FR
282  N952WN
283  N953FR
284  N953WN
285  N954WN
286  N955WN
287  N956WN
288  N957WN
289  N958WN
290  N959WN
291  N960WN
292  N961WN
293  N962WN
294  N963WN
295  N964WN
296  N965WN
297  N966WN
298  N967WN
299  N968WN
300  N969WN

[301 rows x 1 columns]

In [185]:
planes.query("year >= 2010").reset_index()[["tailnum"]]

    tailnum
0    N127UW
1    N128UW
2    N150UW
3    N151UW
4    N152UW
5    N153UW
6    N154UW
7    N155UW
8    N156UW
9    N157UW
10   N198UW
11   N199UW
12   N205FR
13   N206FR
14   N207FR
15   N208FR
16   N20904
17   N209FR
18   N210FR
19   N211FR
20   N213FR
21   N214FR
22   N216FR
23   N26906
24   N272PQ
25   N27477
26   N27901
27   N279PQ
28   N28457
29   N28478
..      ...
271  N913JB
272  N943WN
273  N944WN
274  N945WN
275  N946WN
276  N947WN
277  N948WN
278  N949WN
279  N950WN
280  N951WN
281  N952FR
282  N952WN
283  N953FR
284  N953WN
285  N954WN
286  N955WN
287  N956WN
288  N957WN
289  N958WN
290  N959WN
291  N960WN
292  N961WN
293  N962WN
294  N963WN
295  N964WN
296  N965WN
297  N966WN
298  N967WN
299  N968WN
300  N969WN

[301 rows x 1 columns]

In [187]:
planes[["tailnum"]][planes.year >= 2010].reset_index(drop=True)

    tailnum
0    N127UW
1    N128UW
2    N150UW
3    N151UW
4    N152UW
5    N153UW
6    N154UW
7    N155UW
8    N156UW
9    N157UW
10   N198UW
11   N199UW
12   N205FR
13   N206FR
14   N207FR
15   N208FR
16   N20904
17   N209FR
18   N210FR
19   N211FR
20   N213FR
21   N214FR
22   N216FR
23   N26906
24   N272PQ
25   N27477
26   N27901
27   N279PQ
28   N28457
29   N28478
..      ...
271  N913JB
272  N943WN
273  N944WN
274  N945WN
275  N946WN
276  N947WN
277  N948WN
278  N949WN
279  N950WN
280  N951WN
281  N952FR
282  N952WN
283  N953FR
284  N953WN
285  N954WN
286  N955WN
287  N956WN
288  N957WN
289  N958WN
290  N959WN
291  N960WN
292  N961WN
293  N962WN
294  N963WN
295  N964WN
296  N965WN
297  N966WN
298  N967WN
299  N968WN
300  N969WN

[301 rows x 1 columns]

# 8

In [189]:
sql_result = pd.read_sql_query(
    "SELECT tailnum FROM planes WHERE seats BETWEEN 100 and 200 LIMIT 20", con)
sql_result

   tailnum
0   N102UW
1   N103US
2   N104UW
3   N105UW
4   N107US
5   N108UW
6   N109UW
7   N110UW
8   N111US
9   N11206
10  N112US
11  N113UW
12  N114UW
13  N117UW
14  N118US
15  N119US
16  N12109
17  N12114
18  N12116
19  N12125

In [195]:
planes[(planes.seats >= 100) & (planes.seats <= 200)][["tailnum"]].head(20)

   tailnum
1   N102UW
2   N103US
3   N104UW
5   N105UW
6   N107US
7   N108UW
8   N109UW
9   N110UW
33  N111US
34  N11206
35  N112US
36  N113UW
37  N114UW
46  N117UW
47  N118US
48  N119US
51  N12109
52  N12114
53  N12116
55  N12125

In [194]:
planes.query("seats >= 100 & seats <= 200")[["tailnum"]][:20]

   tailnum
1   N102UW
2   N103US
3   N104UW
5   N105UW
6   N107US
7   N108UW
8   N109UW
9   N110UW
33  N111US
34  N11206
35  N112US
36  N113UW
37  N114UW
46  N117UW
47  N118US
48  N119US
51  N12109
52  N12114
53  N12116
55  N12125

In [199]:
planes[planes.seats.between(100,200,inclusive=True)][["tailnum"]][:20]

   tailnum
1   N102UW
2   N103US
3   N104UW
5   N105UW
6   N107US
7   N108UW
8   N109UW
9   N110UW
33  N111US
34  N11206
35  N112US
36  N113UW
37  N114UW
46  N117UW
47  N118US
48  N119US
51  N12109
52  N12114
53  N12116
55  N12125

In [206]:
"seats >= 100" and "seats <= 200"
# True and costam == costam
# False or costam == costam

'seats <= 200'

In [205]:
"seats >= 100" or "seats <= 200"

'seats >= 100'

In [201]:
pd.DataFrame(planes.query("seats >= 100" and "seats <= 200")["tailnum"]).reset_index(drop=True)

     tailnum
0     N10156
1     N102UW
2     N103US
3     N104UW
4     N10575
5     N105UW
6     N107US
7     N108UW
8     N109UW
9     N110UW
10    N11106
11    N11107
12    N11109
13    N11113
14    N11119
15    N11121
16    N11127
17    N11137
18    N11140
19    N11150
20    N11155
21    N11164
22    N11165
23    N11176
24    N11181
25    N11184
26    N11187
27    N11189
28    N11191
29    N11192
...      ...
2997  N984DL
2998  N985AT
2999  N985DL
3000  N986AT
3001  N986DL
3002  N987AT
3003  N987DL
3004  N988AT
3005  N988DL
3006  N989AT
3007  N989DL
3008  N990AT
3009  N990DL
3010  N991AT
3011  N991DL
3012  N992AT
3013  N992DL
3014  N993AT
3015  N993DL
3016  N994AT
3017  N994DL
3018  N995AT
3019  N995DL
3020  N996AT
3021  N996DL
3022  N997AT
3023  N997DL
3024  N998AT
3025  N998DL
3026  N999DN

[3027 rows x 1 columns]

In [204]:
planes.query("seats > 100 and seats < 200").reset_index().loc[:19,['tailnum']]

   tailnum
0   N102UW
1   N103US
2   N104UW
3   N105UW
4   N107US
5   N108UW
6   N109UW
7   N110UW
8   N111US
9   N11206
10  N112US
11  N113UW
12  N114UW
13  N117UW
14  N118US
15  N119US
16  N12109
17  N12114
18  N12116
19  N12125

# 9

In [215]:
sql_result = pd.read_sql_query(
    'SELECT * FROM planes WHERE manufacturer IN ("BOEING", "AIRBUS", "EMBRAER")', con)
sql_result.shape

(2265, 10)

In [214]:
planes[planes.manufacturer.isin(["BOEING", "AIRBUS", "EMBRAER"])].shape

(2265, 9)

In [219]:
planes.query('manufacturer in ("BOEING", "AIRBUS", "EMBRAER")').shape

(2265, 9)

# 10

In [220]:
pd.read_sql_query('SELECT * FROM planes WHERE manufacturer IN ("BOEING", "AIRBUS", "EMBRAER") AND seats>300', con).shape

(193, 10)

In [221]:
planes.query('manufacturer in ("BOEING", "AIRBUS", "EMBRAER") and seats > 300').shape

(193, 9)

In [222]:
planes.shape

(3322, 9)

# 11

In [225]:
pd.read_sql_query('SELECT manufacturer, COUNT(*) as licznosc FROM planes WHERE seats > 200 GROUP BY manufacturer', con)

       manufacturer  licznosc
0            AIRBUS        66
1  AIRBUS INDUSTRIE         4
2            BOEING       225

In [231]:
planes[planes.seats > 200].groupby("manufacturer").size()\
                                .reset_index().rename({0:"licznosc"}, axis=1)

       manufacturer  licznosc
0            AIRBUS        66
1  AIRBUS INDUSTRIE         4
2            BOEING       225

# 12

In [232]:
pd.read_sql_query('SELECT manufacturer, COUNT(*) FROM planes GROUP BY manufacturer HAVING COUNT(*) > 10', con)

                    manufacturer  COUNT(*)
0                         AIRBUS       336
1               AIRBUS INDUSTRIE       400
2                         BOEING      1630
3                 BOMBARDIER INC       368
4                        EMBRAER       299
5              MCDONNELL DOUGLAS       120
6  MCDONNELL DOUGLAS AIRCRAFT CO       103
7  MCDONNELL DOUGLAS CORPORATION        14

In [236]:
wynik = planes.groupby("manufacturer").size()
wynik[wynik > 10].reset_index()

                    manufacturer     0
0                         AIRBUS   336
1               AIRBUS INDUSTRIE   400
2                         BOEING  1630
3                 BOMBARDIER INC   368
4                        EMBRAER   299
5              MCDONNELL DOUGLAS   120
6  MCDONNELL DOUGLAS AIRCRAFT CO   103
7  MCDONNELL DOUGLAS CORPORATION    14

In [243]:
w = pd.DataFrame(planes.groupby("manufacturer").size())
w[w > 10] # nie, bo w to ramka danych

                                    0
manufacturer
AGUSTA SPA                        NaN
AIRBUS                          336.0
AIRBUS INDUSTRIE                400.0
AMERICAN AIRCRAFT INC             NaN
AVIAT AIRCRAFT INC                NaN
AVIONS MARCEL DASSAULT            NaN
BARKER JACK L                     NaN
BEECH                             NaN
BELL                              NaN
BOEING                         1630.0
BOMBARDIER INC                  368.0
CANADAIR                          NaN
CANADAIR LTD                      NaN
CESSNA                            NaN
CIRRUS DESIGN CORP                NaN
DEHAVILLAND                       NaN
DOUGLAS                           NaN
EMBRAER                         299.0
FRIEDEMANN JON                    NaN
GULFSTREAM AEROSPACE              NaN
HURLEY JAMES LARRY                NaN
JOHN G HESS                       NaN
KILDALL GARY                      NaN
LAMBERT RICHARD                   NaN
LEARJET INC                       NaN
LEBLANC GLENN T                   NaN
MARZ BARRY                        NaN
MCDONNELL DOUGLAS               120.0
MCDONNELL DOUGLAS AIRCRAFT CO   103.0
MCDONNELL DOUGLAS CORPORATION    14.0
PAIR MIKE E                       NaN
PIPER                             NaN
ROBINSON HELICOPTER CO            NaN
SIKORSKY                          NaN
STEWART MACO                      NaN

In [245]:
wynik = planes.groupby("manufacturer")
wynik.filter(lambda x: len(x)>10)

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
5,N105UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
6,N107US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
7,N108UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
8,N109UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
9,N110UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
10,N11106,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
11,N11107,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
12,N11109,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
13,N11113,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
14,N11119,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
15,N11121,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
16,N11127,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
17,N11137,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
18,N11140,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
19,N11150,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
20,N11155,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
21,N11164,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
22,N11165,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
23,N11176,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
24,N11181,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
25,N11184,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
26,N11187,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
27,N11189,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
28,N11191,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
29,N11192,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...
3292,N984DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3293,N985AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3294,N985DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3295,N986AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3296,N986DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3297,N987AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3298,N987DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3299,N988AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3300,N988DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3301,N989AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3302,N989DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3303,N990AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3304,N990DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3305,N991AT,NaN,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3306,N991DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3307,N992AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3308,N992DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3309,N993AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3310,N993DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3311,N994AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3312,N994DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3313,N995AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3314,N995DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3315,N996AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3316,N996DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3317,N997AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3318,N997DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3319,N998AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3320,N998DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3321,N999DN,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet

# 13

In [247]:
pd.read_sql_query('SELECT manufacturer, COUNT(*) FROM planes WHERE seats > 200 GROUP BY manufacturer HAVING COUNT(*) > 10', con)

  manufacturer  COUNT(*)
0       AIRBUS        66
1       BOEING       225

In [251]:
wynik = planes[planes.seats > 200].groupby("manufacturer").size()\
                                .reset_index().rename({0:"licznosc"}, axis=1)
wynik[wynik.licznosc > 10].reset_index(drop=True)

  manufacturer  licznosc
0       AIRBUS        66
1       BOEING       225

# 14

In [252]:
pd.read_sql_query('SELECT manufacturer, COUNT(*) AS howmany FROM planes GROUP BY manufacturer ORDER BY howmany', con)

                     manufacturer  howmany
0                      AGUSTA SPA        1
1              AVIAT AIRCRAFT INC        1
2          AVIONS MARCEL DASSAULT        1
3                   BARKER JACK L        1
4                    CANADAIR LTD        1
5              CIRRUS DESIGN CORP        1
6                     DEHAVILLAND        1
7                         DOUGLAS        1
8                  FRIEDEMANN JON        1
9              HURLEY JAMES LARRY        1
10                    JOHN G HESS        1
11                   KILDALL GARY        1
12                LAMBERT RICHARD        1
13                    LEARJET INC        1
14                LEBLANC GLENN T        1
15                     MARZ BARRY        1
16                    PAIR MIKE E        1
17         ROBINSON HELICOPTER CO        1
18                       SIKORSKY        1
19          AMERICAN AIRCRAFT INC        2
20                          BEECH        2
21                           BELL        2
22           GULFSTREAM AEROSPACE        2
23                   STEWART MACO        2
24                          PIPER        5
25                       CANADAIR        9
26                         CESSNA        9
27  MCDONNELL DOUGLAS CORPORATION       14
28  MCDONNELL DOUGLAS AIRCRAFT CO      103
29              MCDONNELL DOUGLAS      120
30                        EMBRAER      299
31                         AIRBUS      336
32                 BOMBARDIER INC      368
33               AIRBUS INDUSTRIE      400
34                         BOEING     1630

In [260]:
planes.groupby("manufacturer").size().reset_index().rename({0:"howmany"}, axis=1)\
                                .sort_values(by="howmany").reset_index(drop=True)

                     manufacturer  howmany
0                      AGUSTA SPA        1
1                         DOUGLAS        1
2                     DEHAVILLAND        1
3              CIRRUS DESIGN CORP        1
4              HURLEY JAMES LARRY        1
5                    CANADAIR LTD        1
6                     JOHN G HESS        1
7                    KILDALL GARY        1
8                        SIKORSKY        1
9                 LAMBERT RICHARD        1
10                LEBLANC GLENN T        1
11                  BARKER JACK L        1
12         AVIONS MARCEL DASSAULT        1
13             AVIAT AIRCRAFT INC        1
14                     MARZ BARRY        1
15                    PAIR MIKE E        1
16         ROBINSON HELICOPTER CO        1
17                    LEARJET INC        1
18                 FRIEDEMANN JON        1
19                   STEWART MACO        2
20                           BELL        2
21                          BEECH        2
22          AMERICAN AIRCRAFT INC        2
23           GULFSTREAM AEROSPACE        2
24                          PIPER        5
25                         CESSNA        9
26                       CANADAIR        9
27  MCDONNELL DOUGLAS CORPORATION       14
28  MCDONNELL DOUGLAS AIRCRAFT CO      103
29              MCDONNELL DOUGLAS      120
30                        EMBRAER      299
31                         AIRBUS      336
32                 BOMBARDIER INC      368
33               AIRBUS INDUSTRIE      400
34                         BOEING     1630

# 15

In [261]:
pd.read_sql_query('SELECT manufacturer, COUNT(*) AS howmany FROM planes GROUP BY manufacturer ORDER BY howmany DESC LIMIT 10', con)

                    manufacturer  howmany
0                         BOEING     1630
1               AIRBUS INDUSTRIE      400
2                 BOMBARDIER INC      368
3                         AIRBUS      336
4                        EMBRAER      299
5              MCDONNELL DOUGLAS      120
6  MCDONNELL DOUGLAS AIRCRAFT CO      103
7  MCDONNELL DOUGLAS CORPORATION       14
8                       CANADAIR        9
9                         CESSNA        9

In [263]:
planes.groupby("manufacturer").size().reset_index().rename({0:"howmany"}, axis=1)\
                                .sort_values(by="howmany", ascending=False)\
                                .reset_index(drop=True).head(10)

                    manufacturer  howmany
0                         BOEING     1630
1               AIRBUS INDUSTRIE      400
2                 BOMBARDIER INC      368
3                         AIRBUS      336
4                        EMBRAER      299
5              MCDONNELL DOUGLAS      120
6  MCDONNELL DOUGLAS AIRCRAFT CO      103
7  MCDONNELL DOUGLAS CORPORATION       14
8                         CESSNA        9
9                       CANADAIR        9

# 16

In [264]:
pd.read_sql_query('SELECT * FROM planes WHERE year >= 2012 ORDER BY year, seats', con)

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,None,Turbo-shaft
1,815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
2,825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
3,837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
4,2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
5,2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
6,2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
7,2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
8,2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
9,2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
10,2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
11,2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
12,2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
13,2644,N8312C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
14,2645,N8313F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
15,2646,N8314L,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
16,2647,N8315C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
17,2648,N8316H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
18,2649,N8317M,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
19,2650,N8318F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
20,2651,N8319F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
21,2656,N8320J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
22,2657,N8321D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
23,2658,N8322X,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
24,2659,N8323C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
25,2660,N8324A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
26,2661,N8325D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
27,2662,N8326F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
28,2663,N8327A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
29,2664,N8328A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
157,230,N156UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
158,233,N157UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
159,418,N198UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
160,421,N199UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
161,2618,N827JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,None,Turbo-fan
162,2623,N828JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,None,Turbo-fan
163,2675,N834JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,None,Turbo-fan
164,1147,N409AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
165,1160,N413AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
166,1173,N419AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
167,1184,N423AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
168,1207,N431AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
169,1214,N433AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
170,1223,N435AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
171,1241,N440AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
172,1248,N442AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,None,Turbo-fan
173,1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
174,1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
175,1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
176,1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
177,1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
178,1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
179,1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
180,1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
181,1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
182,1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
183,1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
184,2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
185,2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
186,2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan

In [266]:
planes[planes.year >= 2012].sort_values(by=["year", "seats"])

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,NaN,Turbo-shaft
815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2644,N8312C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2645,N8313F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2646,N8314L,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2647,N8315C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2648,N8316H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2649,N8317M,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2650,N8318F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2651,N8319F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2656,N8320J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2657,N8321D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2658,N8322X,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2659,N8323C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2660,N8324A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2661,N8325D,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2662,N8326F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2663,N8327A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2664,N8328A,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...
230,N156UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
233,N157UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
418,N198UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
421,N199UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,NaN,Turbo-fan
2618,N827JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,NaN,Turbo-fan
2623,N828JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,NaN,Turbo-fan
2675,N834JB,2013.0,Fixed wing multi engine,AIRBUS,A320-232,2,200,NaN,Turbo-fan
1147,N409AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1160,N413AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1173,N419AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1184,N423AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1207,N431AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1214,N433AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1223,N435AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1241,N440AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1248,N442AS,2013.0,Fixed wing multi engine,BOEING,737-990ER,2,222,NaN,Turbo-fan
1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan

# 17

In [267]:
pd.read_sql_query('SELECT * FROM planes WHERE year >= 2012 ORDER BY seats, year', con)

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,None,Turbo-shaft
1,815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
2,825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
3,837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
4,843,N354JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
5,848,N355JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
6,859,N358JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
7,908,N368JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
8,956,N373JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
9,989,N374JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
10,1003,N375JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,None,Turbo-fan
11,578,N272PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
12,600,N279PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
13,628,N292PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
14,630,N293PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
15,633,N294PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
16,636,N295PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
17,639,N296PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
18,642,N297PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
19,645,N298PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
20,650,N299PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,None,Turbo-fan
21,2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
22,2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
23,2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
24,2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
25,2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
26,2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
27,2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
28,2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
29,2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,None,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
157,1293,N45905,2012.0,Fixed wing multi engine,BOEING,787-8,2,260,None,Turbo-fan
158,1065,N385HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
159,1068,N386HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
160,1075,N388HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
161,1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
162,1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
163,1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
164,1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
165,1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,None,Turbo-fan
166,1637,N555AY,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
167,1646,N556UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
168,1652,N557UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
169,1657,N558UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
170,1662,N559UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
171,1666,N560UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
172,1670,N561UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
173,1674,N562UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
174,1678,N563UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
175,1683,N564UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
176,1688,N565UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
177,1693,N566UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
178,1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
179,1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
180,1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
181,1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
182,1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
183,1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
184,2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan
185,2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,None,Turbo-fan
186,2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,None,Turbo-fan

In [268]:
planes[planes.year >= 2012].sort_values(by=["seats", "year"])

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
1564,N537JB,2012.0,Rotorcraft,ROBINSON HELICOPTER CO,R66,1,5,NaN,Turbo-shaft
815,N348JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
825,N351JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
837,N353JB,2012.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
843,N354JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
848,N355JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
859,N358JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
908,N368JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
956,N373JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
989,N374JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
1003,N375JB,2013.0,Fixed wing multi engine,EMBRAER,ERJ 190-100 IGW,2,20,NaN,Turbo-fan
578,N272PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
600,N279PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
628,N292PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
630,N293PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
633,N294PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
636,N295PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
639,N296PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
642,N297PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
645,N298PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
650,N299PQ,2013.0,Fixed wing multi engine,BOMBARDIER INC,CL-600-2D24,2,95,NaN,Turbo-fan
2630,N8301J,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2631,N8302F,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2633,N8305E,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2634,N8306H,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2635,N8307K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2636,N8308K,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2637,N8309C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2642,N8310C,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
2643,N8311Q,2012.0,Fixed wing multi engine,BOEING,737-8H4,2,140,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...
1293,N45905,2012.0,Fixed wing multi engine,BOEING,787-8,2,260,NaN,Turbo-fan
1065,N385HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1068,N386HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1075,N388HA,2012.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1083,N390HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1088,N391HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1092,N392HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1096,N393HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1110,N395HA,2013.0,Fixed wing multi engine,AIRBUS,A330-243,2,377,NaN,Turbo-fan
1637,N555AY,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1646,N556UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1652,N557UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1657,N558UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1662,N559UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1666,N560UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1670,N561UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1674,N562UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1678,N563UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1683,N564UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1688,N565UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1693,N566UW,2012.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1696,N567UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1702,N568UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1707,N569UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1713,N570UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1718,N571UW,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
1719,N572UW,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2919,N903JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan
2945,N907JB,2013.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-231,2,379,NaN,Turbo-fan
2982,N913JB,2013.0,Fixed wing multi engine,AIRBUS,A321-231,2,379,NaN,Turbo-fan

# Wybierz 100 losowych wierszy z airports

In [269]:
airports.sample(n=100)

,faa,name,lat,lon,alt,tz,dst,tzone
1013,OLS,Nogales Intl,31.417722,-110.847890,3955,-7,A,America/Phoenix
251,C02,Grand Geneva Resort Airport,42.614917,-88.389583,835,-6,U,America/Chicago
486,FLD,Fond Du Lac County Airport,43.771167,-88.488417,808,-6,A,America/Chicago
954,NEL,Lakehurst Naes,40.033333,-74.353333,103,-5,A,America/New_York
1189,SBA,Santa Barbara Muni,34.426211,-119.840372,10,-8,A,America/Los_Angeles
194,BID,Block Island State Airport,41.168056,-71.577778,108,-5,A,America/New_York
949,N69,Stormville Airport,41.576971,-73.732351,358,-5,A,America/New_York
724,KKB,Kitoi Bay Seaplane Base,58.190833,-152.370556,0,-9,A,America/Anchorage
1361,UTM,Tunica Municipal Airport,34.681000,-90.346700,194,-6,A,America/Chicago
1410,WSD,Condron Aaf,32.341484,-106.402770,3934,-7,A,America/Denver
281,CGC,Crystal River,28.867611,-82.574111,9,-5,A,America/New_York
856,ME5,Banks Airport,44.165389,-68.428167,100,-5,A,America/New_York
370,DKX,Knoxville Downtown Island Airport,35.963833,-83.873667,833,-5,A,America/New_York
1132,RBM,Robinson Aaf,34.850089,-92.300153,587,-6,A,America/Chicago
935,MWA,Williamson Country Regional Airport,37.754957,-89.011094,472,-6,A,America/Chicago
382,DRG,Deering Airport,66.069600,-162.766000,21,-9,A,America/Anchorage
1220,SGJ,St. Augustine Airport,29.959250,-81.339722,10,-5,A,America/New_York
915,MRI,Merrill Fld,61.213544,-149.844447,137,-9,A,America/Anchorage
335,CVS,Cannon Afb,34.382775,-103.322147,4295,-7,A,America/Denver
465,FAI,Fairbanks Intl,64.815114,-147.856267,434,-9,A,America/Anchorage
211,BLD,Boulder City Municipal Airport,35.565100,-114.514000,2201,-7,U,America/Phoenix
1265,SRV,Stony River 2 Airport,61.787500,-156.591111,230,-9,A,America/Anchorage
788,LGC,LaGrange-Callaway Airport,33.008861,-85.072611,694,-5,A,America/New_York
1121,PWK,Chicago Executive,42.114290,-87.901538,647,-6,A,America/Chicago
1227,SHR,Sheridan County Airport,44.769200,-106.980000,4021,-7,A,America/Denver
682,IYK,Inyokern Airport,35.658889,-117.829444,2455,-8,A,America/Los_Angeles
1016,OMA,Eppley Afld,41.303167,-95.894069,984,-6,A,America/Chicago
599,HNH,Hoonah Airport,58.096111,-135.409722,19,-9,A,America/Anchorage
722,KGX,Grayling Airport,62.894444,-160.065000,99,-9,A,America/Anchorage
210,BKX,Brookings Regional Airport,44.304800,-96.816900,1648,-6,A,America/Chicago
...,...,...,...,...,...,...,...,...
413,ECP,Panama City-NW Florida Bea.,30.341700,-85.797300,69,-6,A,America/Chicago
471,FBR,Fort Bridger,41.236000,-110.243600,7038,-7,A,America/Denver
395,DVL,Devils Lake Regional Airport,48.114444,-98.908611,1445,-6,A,America/Chicago
1011,OLH,Old Harbor Airport,57.218056,-153.269722,55,-9,A,America/Anchorage
964,NIP,Jacksonville Nas,30.235834,-81.680556,22,-5,A,America/New_York
853,MCW,Mason City Municipal,43.224700,-93.406700,1243,-6,A,America/Chicago
202,BJI,Bemidji Regional Airport,47.510722,-94.934722,1391,-6,A,America/Chicago
817,LSE,La Crosse Municipal,43.878986,-91.256711,654,-6,A,America/Chicago
259,CAR,Caribou Muni,46.871500,-68.017917,626,-5,A,America/New_York
764,LAL,Lakeland Linder Regional Airport,27.988917,-82.018556,142,-5,A,America/New_York
1316,TMA,Henry Tift Myers Airport,31.428981,-83.488545,355,-5,A,America/New_York
67,6S2,Florence,43.982817,-124.111369,51,-8,A,America/Los_Angeles
470,FBK,Ladd Aaf,64.837500,-147.614444,454,-9,A,America/Anchorage
699,JOT,Regional Airport,41.517778,-88.175556,582,-6,A,America/Chicago
1168,ROC,Greater Rochester Intl,43.118866,-77.672389,559,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
126,AMA,Rick Husband Amarillo Intl,35.219369,-101.705931,3607,-6,A,America/Chicago
1241,SLN,Salina Municipal Airport,38.791000,-97.652200,1288,-6,A,America/Chicago
285,CGZ,Casa Grande Municipal Airport,32.954889,-111.766832,1464,-7,U,America/Phoenix
609,HPB,Hooper Bay Airport,61.523900,-166.147000,7,-9,A,America/Anchorage
1277,SUN,Friedman Mem,43.504444,-114.296194,5320,-7,A,America/Denver
188,BFT,Beaufort,32.477411,-80.723161,37,-5,A,America/New_York
687,JBR,Jonesboro Muni,35.831708,-90.646417,262,-6,A,America/Chicago
423,EGV,Eagle River,45.932333,-89.268283,1642,-6,A,America/Chicago
595,HLG,Wheeling Ohio County Airport,40.175000,-80.646300,1195,-5,A,America/New_York
350,CZN,Chisana Airport,62.071111,-142.048333,1011,-9,A,America/Anchorage
711,KAE,Kake Seaplane Base,56.973056,-133.945556,0,-9,A,America/Anchorage
303,CLL,Easterwood Fld,30.588583,-96.363833,321,-6,A,America/Chicago
1328,TPL,Draughon Miller Central Texas Rgnl,31.152500,-97.407778,682,-6,A,America/Chicago
842,MBS,Mbs Intl,43.532913,-84.079647,668,-5,A,America/New_York

# Wybierz 5% losowych wierszy

In [275]:
airports.sample(frac=0.05)

,faa,name,lat,lon,alt,tz,dst,tzone
496,FNR,Funter Bay Seaplane Base,58.254444,-134.897778,0,-9,A,America/Anchorage
869,MGW,Morgantown Muni Walter L Bill Hart Fld,39.642908,-79.916314,1248,-5,A,America/New_York
1008,OJC,Johnson County Airport,38.505100,-94.441500,1096,-6,A,America/Chicago
827,LVS,Las Vegas Muni,35.654222,-105.142389,6877,-7,A,America/Denver
446,ERI,Erie Intl Tom Ridge Fld,42.082022,-80.176217,733,-5,A,America/New_York
1222,SGU,St George Muni,37.090583,-113.593056,2941,-7,A,America/Denver
1368,VAY,South Jersey Regional Airport,39.942889,-74.845750,53,-5,A,America/New_York
1245,SMF,Sacramento Intl,38.695417,-121.590778,27,-8,A,America/Los_Angeles
336,CVX,Charlevoix Municipal Airport,45.304778,-85.275333,669,-5,A,America/New_York
447,ERV,Kerrville Municipal Airport,29.976667,-99.085472,1617,-6,A,America/Chicago
214,BLI,Bellingham Intl,48.792694,-122.537528,170,-8,A,America/Los_Angeles
1141,RDR,Grand Forks Afb,47.961098,-97.401194,913,-6,A,America/Chicago
1213,SFB,Orlando Sanford Intl,28.777639,-81.237489,55,-5,A,America/New_York
1194,SBP,San Luis County Regional Airport,35.236800,-120.642000,212,-8,A,America/Los_Angeles
1129,RAP,Rapid City Regional Airport,44.045278,-103.057222,3204,-7,A,America/Denver
1015,OLV,Olive Branch Muni,34.876944,-89.783333,350,-6,A,America/Chicago
453,EUF,Weedon Field,31.570800,-85.077400,285,-6,A,America/Chicago
1080,PIM,Harris County Airport,32.840694,-84.882444,902,-5,A,America/New_York
1341,TWA,Twin Hills Airport,59.074444,-160.275000,82,-9,A,America/Anchorage
204,BKD,Stephens Co,32.719047,-98.891000,1284,-6,A,America/Chicago
640,IAH,George Bush Intercontinental,29.984433,-95.341442,97,-6,A,America/Chicago
1266,SSC,Shaw Afb,33.972719,-80.470564,242,-5,A,America/New_York
1311,TKI,Collin County Regional Airport at Mc Kinney,33.177944,-96.590528,585,-6,A,America/Chicago
959,NGU,Norfolk Ns,36.937644,-76.289289,15,-5,A,America/New_York
984,NUP,Nunapitchuk Airport,60.905833,-162.439167,12,-9,A,America/Anchorage
751,KVL,Kivalina Airport,67.736200,-164.563000,13,-9,A,America/Anchorage
1403,WKL,Waikoloa Heliport,19.913600,-155.864000,109,-10,N,Pacific/Honolulu
97,ADQ,Kodiak,57.749967,-152.493856,78,-9,A,America/Anchorage
519,GAD,Northeast Alabama Regional Airport,33.972649,-86.089083,569,-6,A,America/Chicago
124,ALX,Alexandria,38.806346,-77.062100,1,-5,A,America/New_York
...,...,...,...,...,...,...,...,...
482,FFZ,Mesa Falcon Field,33.460800,-111.727997,1394,-7,A,America/Phoenix
540,GJT,Grand Junction Regional,39.122413,-108.526735,4858,-7,A,America/Denver
595,HLG,Wheeling Ohio County Airport,40.175000,-80.646300,1195,-5,A,America/New_York
1273,STL,Lambert St Louis Intl,38.748697,-90.370028,618,-6,A,America/Chicago
745,KSM,St Marys Airport,62.060500,-163.302000,311,-9,A,America/Anchorage
646,IFP,Laughlin-Bullhead Intl,35.157400,-114.560000,695,-7,A,America/Phoenix
1134,RBY,Ruby Airport,64.727200,-155.470000,653,-9,A,America/Anchorage
1447,ZRT,Hartford Union Station,41.768880,-72.681500,0,-5,A,America/New_York
1244,SME,Lake Cumberland Regional Airport,37.053611,-84.615556,927,-5,A,America/New_York
1383,VPS,Eglin Afb,30.483250,-86.525400,87,-6,A,America/Chicago
746,KTB,Thorne Bay Seaplane Base,55.688056,-132.536667,0,-9,A,America/Anchorage
1124,PYM,Plymouth Municipal Airport,41.909028,-70.728778,148,-5,A,America/New_York
499,FOE,Forbes Fld,38.950944,-95.663611,1078,-6,A,America/Chicago
153,ATL,Hartsfield Jackson Atlanta Intl,33.636719,-84.428067,1026,-5,A,America/New_York
733,KNW,New Stuyahok Airport,59.449900,-157.328000,302,-9,A,America/Anchorage
803,LNN,Lost Nation Municipal Airport,41.684028,-81.389750,626,-5,A,America/New_York
677,ISW,Alexander Field South Wood County Airport,44.360646,-89.838141,1021,-6,A,America/Chicago
1304,TEX,Telluride,37.953759,-107.908480,9078,-7,A,America/Denver
581,HDI,Hardwick Field Airport,35.219999,-84.832369,874,-5,A,America/New_York
427,EKI,Elkhart Municipal,41.719444,-86.003333,778,-5,A,America/New_York
878,MIC,Crystal Airport,45.034300,-93.211400,869,-6,A,America/Chicago
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
1052,PBF,Grider Fld,34.173142,-91.935597,206,-6,A,America/Chicago
1053,PBG,Plattsburgh Intl,44.650944,-73.468139,234,-5,A,America/New_York
1348,TZR,Bolton Field,39.901111,-83.136944,905,-5,A,America/New_York
504,FRP,St Lucie County International Airport,27.497472,-80.372638,23,-5,A,America/New_York
445,EQY,Monroe Reqional Airport,35.018330,-80.620010,679,-5,A,America/New_York
1262,SQL,San Carlos Airport,37.511944,-122.249444,5,-8,A,America/Los_Angeles
412,ECG,Elizabeth City Cgas Rgnl,36.260581,-76.174572,12,-5,A,America/New_York
125,ALZ,Alitak Seaplane Base,56.899444,-154.247778,0,-9,A,America/Anchorage

# Wybierz pierwszych 100 wierszy

In [276]:
airports.head(100)

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York
15,1B9,Mansfield Municipal,42.000133,-71.196771,122,-5,A,America/New_York
16,1C9,Frazier Lake Airpark,54.013333,-124.768333,152,-8,A,America/Vancouver
17,1CS,Clow International Airport,41.695974,-88.129231,670,-6,U,America/Chicago
18,1G3,Kent State Airport,41.151389,-81.415111,1134,-5,A,America/New_York
19,1G4,Grand Canyon West Airport,35.899904,-113.815674,4813,-7,A,America/Phoenix
20,1H2,Effingham Memorial Airport,39.070000,-88.534000,585,-6,A,America/Chicago
21,1OH,Fortman Airport,40.555325,-84.386619,885,-5,U,America/New_York
22,1RL,Point Roberts Airpark,48.979722,-123.078889,10,-8,A,America/Los_Angeles
23,23M,Clarke CO,32.051700,-88.443400,320,-6,A,America/Chicago
24,24C,Lowell City Airport,42.953920,-85.343906,681,-5,A,America/New_York
25,24J,Suwannee County Airport,30.300125,-83.024694,104,-5,A,America/New_York
26,25D,Forest Lake Airport,45.247746,-92.994385,925,-6,A,America/Chicago
27,29D,Grove City Airport,41.146028,-80.167750,1371,-5,A,America/New_York
28,2A0,Mark Anton Airport,35.486250,-84.931083,718,-5,A,America/New_York
29,2B2,Plum Island Airport,42.795361,-70.839444,11,-5,A,America/New_York
...,...,...,...,...,...,...,...,...
70,70N,Spring Hill Airport,41.347357,-75.415897,1729,-5,A,America/New_York
71,7A4,Foster Field,42.466444,-90.169389,990,-6,A,America/Chicago
72,7D9,Germack Airport,41.777832,-80.903980,820,-5,A,America/New_York
73,7N7,Spitfire Aerodrome,39.735563,-75.397721,40,-5,A,America/New_York
74,8M8,Garland Airport,44.806528,-84.276194,1218,-5,A,America/New_York
75,93C,Richland Airport,43.283358,-90.298282,742,-6,A,America/Chicago
76,99N,Bamberg County Airport,33.304528,-81.108417,231,-5,A,America/New_York
77,9A1,Covington Municipal Airport,33.632308,-83.847447,809,-5,A,America/New_York
78,9A5,Barwick Lafayette Airport,34.688479,-85.290332,777,-5,A,America/New_York
79,9G1,Rock Airport,40.603546,-79.826119,1063,-5,A,America/New_York
80,A39,Phoenix Regional Airport,32.991699,-111.920998,1300,-7,A,America/Phoenix
81,A50,Colorado Springs East,38.870000,-104.410000,6145,-7,A,America/Denver
82,AAF,Apalachicola Regional Airport,29.727607,-85.027442,20,-5,A,America/New_York
83,AAP,Andrau Airport,29.430000,-95.350000,80,-6,A,America/Chicago
84,ABE,Lehigh Valley Intl,40.652083,-75.440806,393,-5,A,America/New_York
85,ABI,Abilene Rgnl,32.411319,-99.681897,1791,-6,A,America/Chicago
86,ABL,Ambler Airport,67.106389,-157.857500,334,-9,A,America/Anchorage
87,ABQ,Albuquerque International Sunport,35.040222,-106.609194,5355,-7,A,America/Denver
88,ABR,Aberdeen Regional Airport,45.449100,-98.421800,1302,-6,A,America/Chicago
89,ABY,Southwest Georgia Regional Airport,31.535500,-84.194500,197,-5,A,America/New_York
90,ACJ,Jimmy Carter Regional,32.066500,-84.113300,468,-5,A,America/New_York
91,ACK,Nantucket Mem,41.253053,-70.060181,48,-5,A,America/New_York
92,ACT,Waco Rgnl,31.611289,-97.230519,516,-6,A,America/Chicago
93,ACV,Arcata,40.978111,-124.108611,221,-8,A,America/Los_Angeles
94,ACY,Atlantic City Intl,39.457583,-74.577167,75,-5,A,America/New_York
95,ADK,Adak Airport,51.878000,-176.646000,18,-9,A,America/Anchorage
96,ADM,Ardmore Muni,34.300833,-97.008889,762,-6,A,America/Chicago
97,ADQ,Kodiak,57.749967,-152.493856,78,-9,A,America/Anchorage
98,ADS,Addison,32.968559,-96.836448,644,-6,A,America/Chicago
99,ADW,Andrews Afb,38.810806,-76.867028,280,-5,A,America/New_York

* `M` - markdown
* `Y` - Python
* `ESC` - wyj≈õƒá z kom√≥rki

# Ostatnie 100 wierszy

In [277]:
airports.tail(100)

,faa,name,lat,lon,alt,tz,dst,tzone
1358,UPP,Upolu,20.265256,-155.859989,96,-10,A,Pacific/Honolulu
1359,UST,St. Augustine Airport,29.959167,-81.339722,10,-5,A,America/New_York
1360,UT3,Hite Airport,37.891655,-110.384029,3840,-7,A,America/Denver
1361,UTM,Tunica Municipal Airport,34.681000,-90.346700,194,-6,A,America/Chicago
1362,UTO,Indian Mountain Lrrs,65.992794,-153.704289,1220,-9,A,America/Anchorage
1363,UUK,Ugnu-Kuparuk Airport,70.330833,-149.597500,67,-9,A,America/Anchorage
1364,UUU,Newport State,41.533056,-71.282222,172,-5,A,America/New_York
1365,UVA,Garner Field,29.215429,-99.748962,942,-6,A,America/Chicago
1366,VAD,Moody Afb,30.967833,-83.193000,233,-5,A,America/New_York
1367,VAK,Chevak Airport,61.533800,-165.584000,75,-9,A,America/Anchorage
1368,VAY,South Jersey Regional Airport,39.942889,-74.845750,53,-5,A,America/New_York
1369,VBG,Vandenberg Afb,34.737333,-120.584306,369,-8,A,America/Los_Angeles
1370,VCT,Victoria Regional Airport,28.852600,-96.918500,115,-6,A,America/Chicago
1371,VCV,Southern California Logistics,34.597453,-117.382997,2885,-8,A,America/Los_Angeles
1372,VDF,Tampa Executive Airport,28.013977,-82.345278,22,-5,A,America/New_York
1373,VDZ,Valdez Pioneer Fld,61.133949,-146.248342,118,-9,A,America/Anchorage
1374,VEE,Venetie Airport,67.008611,-146.366389,574,-9,A,America/Anchorage
1375,VEL,Vernal Regional Airport,40.440833,-109.510000,5278,-7,A,America/Denver
1376,VGT,North Las Vegas Airport,36.210694,-115.194444,2205,-8,U,America/Los_Angeles
1377,VIS,Visalia Municipal Airport,36.318611,-119.392778,295,-8,A,America/Los_Angeles
1378,VLD,Valdosta Regional Airport,30.782500,-83.276700,203,-5,A,America/New_York
1379,VNW,Van Wert County Airport,40.863830,-84.606358,787,-5,A,America/New_York
1380,VNY,Van Nuys,34.209811,-118.489972,802,-8,A,America/Los_Angeles
1381,VOK,Volk Fld,43.938956,-90.253433,912,-6,A,America/Chicago
1382,VPC,Cartersville Airport,34.123147,-84.848707,759,-5,A,America/New_York
1383,VPS,Eglin Afb,30.483250,-86.525400,87,-6,A,America/Chicago
1384,VRB,Vero Beach Muni,27.655556,-80.417944,24,-5,A,America/New_York
1385,VSF,Hartness State,43.343333,-72.517222,577,-5,A,America/New_York
1386,VYS,Illinois Valley Regional,41.351944,-89.153056,654,-6,A,America/Chicago
1387,W04,Ocean Shores Municipal,46.599500,-124.085400,15,-8,A,America/Los_Angeles
...,...,...,...,...,...,...,...,...
1428,X59,Valkaria Municipal,27.960861,-80.558333,26,-5,A,America/New_York
1429,XFL,Flagler County Airport,29.282100,-81.121200,33,-5,A,America/New_York
1430,XNA,NW Arkansas Regional,36.281869,-94.306811,1287,-6,A,America/Chicago
1431,XZK,Amherst Amtrak Station AMM,42.375000,-72.511389,258,-5,A,America/New_York
1432,Y51,Municipal Airport,43.579360,-90.896474,1292,-6,A,America/Chicago
1433,Y72,Bloyer Field,43.976222,-90.480611,966,-6,A,America/Chicago
1434,YAK,Yakutat,59.301200,-139.393700,33,-9,A,\N
1435,YIP,Willow Run,42.237928,-83.530408,716,-5,A,America/New_York
1436,YKM,Yakima Air Terminal McAllister Field,46.568200,-120.544000,1095,-8,A,America/Los_Angeles
1437,YKN,Chan Gurney,42.871100,-97.396900,1200,-6,A,America/Chicago
1438,YNG,Youngstown Warren Rgnl,41.260736,-80.679097,1196,-5,A,America/New_York
1439,YUM,Yuma Mcas Yuma Intl,32.656578,-114.605980,216,-7,N,America/Phoenix
1440,Z84,Clear,64.301203,-149.120144,552,-9,A,America/Anchorage
1441,ZBP,Penn Station,39.307222,-76.615556,66,-5,A,America/New_York
1442,ZFV,Philadelphia 30th St Station,39.955700,-75.182000,0,-5,A,America/New_York
1443,ZPH,Municipal Airport,28.228056,-82.155833,90,-5,A,America/New_York
1444,ZRA,Atlantic City Rail Terminal,39.366500,-74.442000,8,-5,A,America/New_York
1445,ZRD,Train Station,37.534300,-77.429450,26,-5,A,America/New_York
1446,ZRP,Newark Penn Station,40.734722,-74.164167,0,-5,A,America/New_York
1447,ZRT,Hartford Union Station,41.768880,-72.681500,0,-5,A,America/New_York
1448,ZRZ,New Carrollton Rail Station,38.948000,-76.871900,39,-5,A,America/New_York
1449,ZSF,Springfield Amtrak Station,42.106000,-72.593054,65,-5,A,America/New_York
1450,ZSY,Scottsdale Airport,33.622889,-111.910528,1519,-7,A,America/Phoenix
1451,ZTF,Stamford Amtrak Station,41.046937,-73.541493,0,-5,A,America/New_York
1452,ZTY,Boston Back Bay Station,42.347800,-71.075000,20,-5,A,America/New_York
1453,ZUN,Black Rock,35.083228,-108.791778,6454,-7,A,America/Denver
1454,ZVE,New Haven Rail Station,41.298669,-72.925992,7,-5,A,America/New_York
1455,ZWI,Wilmington Amtrak Station,39.736667,-75.551667,0,-5,A,America/New_York
1456,ZWU,Washington Union Station,38.897460,-77.006430,76,-5,A,America/New_York
1457,ZYP,Penn Station,40.750500,-73.993500,35,-5,A,America/New_York

# Teoriomnogo≈õciowe

In [279]:
A = airports[0:10]
B = airports[5:15]

In [280]:
A.shape

(10, 8)

In [281]:
B.shape

(10, 8)

### SELECT * FROM A UNION ALL SELECT * FROM B

In [285]:
pd.concat([A,B])

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York

In [286]:
A.append(B)

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York

### SELECT * FROM A UNION SELECT * FROM B

In [289]:
pd.concat([A,B]).drop_duplicates()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York

### SELECT * FROM A INTERSECT SELECT * FROM B

In [292]:
A

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles

In [296]:
A.isin(B)

     faa   name    lat    lon    alt     tz    dst  tzone
0  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False
5   True   True   True   True   True   True   True   True
6   True   True   True   True   True   True   True   True
7   True   True   True   True   True   True   True   True
8   True   True   True   True   True   True   True   True
9   True   True   True   True   True   True   True   True

In [295]:
A[A.isin(B)].dropna()

,faa,name,lat,lon,alt,tz,dst,tzone
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593.0,-5.0,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730.0,-5.0,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492.0,-5.0,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000.0,-5.0,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108.0,-8.0,A,America/Los_Angeles

In [298]:
wynik = pd.concat([A,B])
wynik[wynik.duplicated()]

,faa,name,lat,lon,alt,tz,dst,tzone
5,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles

In [300]:
pd.merge(A,B)

,faa,name,lat,lon,alt,tz,dst,tzone
0,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
1,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
2,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
3,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
4,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles

# SELECT * FROM A EXCEPT SELECT * FROM B

In [305]:
A[~A.isin(B)].dropna()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044.0,-5.0,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264.0,-6.0,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801.0,-6.0,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523.0,-5.0,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11.0,-5.0,A,America/New_York